-- Active: 1751394111506@@127.0.0.1@5432@gophkeeper
-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS secrets (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL,
    value text NOT NULL,
    user_id int NOT NULL,
    version_id BIGINT DEFAULT 1,
    creation_date timestamp NOT NULL,
    updating_date timestamp NOT NULL,
    deletion_mark BOOLEAN DEFAULT FALSE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE secrets;
-- +goose StatementEnd
